### ISSUE TITLE
Wrong usage ?

### ISSUE THREAD

**Issue by brasseld** [apiman/apiman-studio#23]
Hello guys,

I would like to have a try to the apiman designer.
Not sure if I'm doing something wrong, but I've created a github repository including a OAI definition ([https://github.com/brasseld/apiman-studio-test](url)).

It seems that there are some CORS issues:
<img width="1412" alt="capture d ecran 2016-12-21 a 10 06 56" src="https://cloud.githubusercontent.com/assets/133094/21383302/4c2c70d4-c765-11e6-889d-26b8e78b73b4.png">

Also, my github password appears in clear in the session storage and I'm not sure it's a good idea.

Thanks for your feedback.

**Comment by EricWittmann** [comment]
Hey @brasseld - thanks for the interest in the API designer.  It's still VERY much a work in progress and nowhere near a usable state.  I'm hoping to have something minimally useful/functional by the end of January.  So I wouldn't recommend trying out the project until at least that time.  (In fact, the actual OAI editor component isn't written at all yet.)

That said - the error you are seeing seems to be because the github information you entered into the Create API form was slightly incorrect.  Your OAI document resides in this repo:

https://github.com/brasseld/apiman-studio-test

But that's not the URL I'm seeing in the screenshot you provided.  The easiest way to add an API to the studio is to drag and drop the URL of the resource from the browser onto the Create API form.  If you do that, everything will be auto-populated appropriately.

I'd be happy to hear any feedback you might have as the project progresses!

PS: good point regarding the password being stored in the clear.  I'll add a ticket for that specific issue.

**Comment by brasseld** [comment]
I really (really) need holidays ! Sorry to disturb you with such issue....
It works like a charm using D&D feature.

I would be happy to provide you with more feedbacks as soon as the project will be more usable / functional.

Regards,

**Comment by EricWittmann** [comment]
Yeah I'm right there with you regarding the need for the holiday.  :)
