### ISSUE TITLE
Add <!DOCTYPE html> to index

### ISSUE THREAD

**Issue by msavy** [apiman/apiman-studio#38]
Currently it's running in quirks mode, and when standards mode is enabled the CSS breaks.

**Comment by EricWittmann** [comment]
Which CSS breaks?

**Comment by msavy** [comment]
Seeing it yourself is probably easier than describing (just paste the doctype at the top of index.html)

Seemingly several bits seem to  break - it seems to be something to do with `.cards-pf`which is overriding the background colours for every element. 

If you force with `body { background: #363636 !important }` you see the expected patterns (nice colour!). But obviously not a proper fix. 

I’m still not completely familiar with the CSS debugger; been trying to trace the culprit more accurately.

**Comment by EricWittmann** [comment]
I don't see any problems with background colors when I switch to standards mode.  With the exception of the login screen, which does break.

However, there ARE some problems that I do see.  Fortunately all the work I did on the static mockups were using standards mode.  So there shouldn't be TOO many issues since I mostly just copied that markup over when doing the angular2 impl.

**Comment by msavy** [comment]
Oh, indeed, I was mainly talking about the logon screen.
